// Shape of the api.json files generated by `pnpm docs:api` (scripts/gen-api.mjs)
// and rendered by <ApiReference>.

export interface ApiProp {
	name: string;
	type: string;
	required: boolean;
	default: string | null;
	description: string;
}

export interface ApiDataAttribute {
	name: string;
	description: string;
}

export interface ApiPart {
	name: string;
	description: string;
	/**
	 * The HTML or SVG element that the part makes, when the part also takes the
	 * attributes of that element. A mark and a guide take only their own props.
	 */
	element?: string;
	props: ApiProp[];
	dataAttributes: ApiDataAttribute[];
}

export interface ComponentApi {
	component: string;
	parts: ApiPart[];
}
